### ISSUE TITLE
allow-unsafe doesn't properly work with included files

### ISSUE THREAD

**Issue by leos** [jazzband/pip-tools#1131]
#### Environment Versions

1. Ubuntu 18.04
1. Python version: Python 3.7.5
1. pip version:  20.1
1. pip-tools version: 5.1.1

#### Steps to replicate

1. Create two test files:
```
# test.in
-c bar.lock
pylint~=2.4
```
```
# bar.lock
click==7.1.2
pip-tools==5.1.1
six==1.14.0
pip==20.1
setuptools==46.1.3
```
2. run `pip-compile test.in --no-annotate --no-header --allow-unsafe`

#### Expected result
Output should contain all of the locked requirements from `bar.lock`.

#### Actual result
Output does not contain requirements from `bar.lock`

If the contents of `bar.lock` are inserted into `test.in` - or even if it's just `pip-tools`, `pip` and `setuptools` w/o their transitive dependencies, `--allow-unsafe` works properly.

**Comment by atugushev** [comment]
Hello @leos,

Thanks for the issue! It not related to `--allow-unsafe` options. I'm afraid this is how pip-tools (and pip by the way) works with constraint files. Let me explain. Suppose you have the following constraint file:

```ini
# constraints.txt
six==1.10.0
pytz==2019.3
```

and `requirements.in` file:

```ini
-c constraints.txt
six
click
```

The result of `pip-compile --no-header` would be:

```
six==1.10.0
click==7.1.2
```

What's happened:
- `six` resolved to `1.10.0` version because it was constrained in `constraints.txt`, despite on the latest version is `1.14.0`.
- `click` resolved to the latest version `7.1.2` since there is no constraints for it.
- `pytz` didn't get into the output since it's a constraint, not a direct dependency.

`pip-tools` doesn't compile constraints from constraint files to the output, but respects given versions for direct dependencies.

Also, you might find useful [this section](https://github.com/jazzband/pip-tools#workflow-for-layered-requirements) where described the main use-case with constraint files.

**Comment by leos** [comment]
Ah, got it, thanks for the explanation and the prompt response.

That makes total sense. I treated `constraints` as an include and that's not correct.

**Comment by atugushev** [comment]
Happy to help. Don't hesitate to reach out if you have any other issues. Thanks!
