### ISSUE TITLE
Deprecate legacy resolver

### ISSUE THREAD

**Issue by atugushev** [jazzband/pip-tools#1659]
#### What's the problem this feature will solve?

Pip's legacy resolver is going to be removed any time soon, let's prepare for it.

#### Describe the solution you'd like

Deprecate the legacy resolver and remove it as soon as pip removes its own legacy resolver.

#### Alternative Solutions

Vendoring?. We've gone that path before but that didn't help.

#### Additional context

- https://github.com/pypa/pip/issues/10946
- https://github.com/pypa/pip/milestone/47

**Comment by AndydeCleyre** [comment]
> In the mean time, maybe activate backtracking by default?

I just want to note here that we should at least close #1647 before or at the same time as making that change.

**Comment by atugushev** [comment]
> In the mean time, maybe activate backtracking by default?

We'll do it in `7.0.0` because it's a breaking change.

**Comment by atugushev** [comment]
Pinning the issue to bring more attention.

**Comment by jikuja** [comment]
https://github.com/jazzband/pip-tools/issues/1752 mentions following:
> --strip-extras, because otherwise using --resolver=backtracking failed with Constraints cannot have extras

This should be documented. 

----

In my use case:
```
pyjwt[crypto]==2.4.0
    # via msal
```
is generated into requirements.txt file and then compiling dev-requirements.in
```
-c requirements.txt
debugpy==1.6.2
```
with `pip-compile --resolver=backtracking dev-requirements.in`

throws `pip._internal.exceptions.InstallationError: Constraints cannot have extras`

**Comment by ssbarnea** [comment]
To be honest, I would make strip extras implicit because I never has a need to use pip-tools for something else than updating constraint files, so adding this parameter is annoying at best. There are lots of problems with extras other than not being allowed for constraints.

PS. To be clear, I use extras in all my projects, just I never need the in the output.

**Comment by ThiefMaster** [comment]
I'm the maintainer of an [end application](https://github.com/indico/indico/), it is meant to be installed in a clean env, so we pin everything for fully reproducible installs: the pip-compile output goes straight into the package's `install_requires`.

But we also have a set of dev dependencies which are constrained by the main runtime dependencies since developers install them in the same environment - so we have `-c requirements.txt` in our `requirements.dev.in`.

However, one of the dependencies we have is `bleach[css]`. That extra is not optional, we need the functionality this pulls in.

Or is this not necessary because extras are *only* used to pull in additional dependencies and thus omitting them at install time is not a problem as long as those other dependencies are installed anyway (which is the case here)?
