### ISSUE TITLE
Should pip-tools be included in requirements.in or dev-requirements.in file?

### ISSUE THREAD

**Issue by OmerFI** [jazzband/pip-tools#1679]
Hi,

Should pip-tools be included in **requirements.in** or **dev-requirements.in** file?

**Comment by AndydeCleyre** [comment]
IMO it's just up to you and your team, but I don't include it. Instead, the shell functions I use for creating/activating venvs ensure that pip-tools is installed. 

One reason my choice is that others using the project, who want to install even dev dependencies, don't necessarily need pip-tools at all, since they can just `pip install -r dev-requirements.txt`.

That said, I can see it making a lot of sense to include it if, for example, you have a set of task-runner/makefile-ish commands that invoke pip-tools commands, so all your devs need them available.

**Comment by OmerFI** [comment]
Thanks!
