### ISSUE TITLE
What version is covered by the official documentation?

### ISSUE THREAD

**Issue by berislavlopac** [jazzband/pip-tools#1777]
The `pip-tools` version displayed on the [official documentation](https://pip-tools.readthedocs.io) site is listed as `6.10.1.dev11+g6839a64.d20221120`, and the [changelog page](https://pip-tools.readthedocs.io/en/latest/changelog/) shows the latest version as `6.10.0 (2022-11-13)`; however, the actual version installed with `pip install pip-tools` is `6.12.0`. 

So I'm not sure: is the documentation in line with the latest version, and only the version number is not displayed, or is there a failure when building the documentation for the latest version? Or am I missing something obvious? 🤔

**Comment by webknjaz** [comment]
The docs are built on pushes to master and the "long" version means the distance to the previous git tag + the exact commit. Maybe something was broken when the last release was being made — somebody could forget to update the changelog since this prerequisite process is rather disconnected from the main release workflow.

**Comment by webknjaz** [comment]
So it looks like the stable version was built roughly 13 hours ago but the latest one got updated 3 weeks and 3 days ago.
Best guess is that this correctes with renaming master to main.

**Comment by webknjaz** [comment]
I've switched the branch for `latest` to `main` so it is sorted now.

Additionally, https://pip-tools.rtfd.io/en/stable is rebuilt on the last tag pushed.
