### ISSUE TITLE
Can't install click itself

### ISSUE THREAD

**Issue by nvie** [jazzband/pip-tools#305]
pip-tools ignores its own dependencies. Click is one of them.

To replicate:
1. Install pip-tools globally, not in the target env.
2. `echo click > requirements.in`
3. `pip-compile`
4. `pip-sync`

Expected result: click is installed.

Actual result: click is not installed.

**Comment by davidovich** [comment]
click is already a sub dependency of pip-tools. I suppose this is ok for now. Closing.

**Comment by rpkilby** [comment]
@davidovich - not sure if this should be closed. I don't use pip-tools in my target environments and just do a `pip install -r requirements.txt` on a clean `virtualenv`. Since pip-tools isn't installed, neither would click.

**Comment by davidovich** [comment]
@rpkilby I don't quite get what you mean. The issue states a repro step where click is mentioned in requirements.in, and a run of pip-compile and pip-sync is run. I have observed locally that click is indeed installed. 

This was an issue regarding pip-tools, but you are saying that you do not have pip-tools installed.

I am trying to tidy up the project somewhat, so I may have closed prematurely. But I still have very little to run on for this over one year old issue.

**Comment by rpkilby** [comment]
sorry for the noise - I misread the issue. I thought the issue was that `pip-compile` was not including `click` in its output because of the self-dependency issue. The issue seems to have instead been w/ `pip-sync`.

In my case, I use pip-tools locally to create the version locked requirements.txt, however I just use regular `pip`, not `pip-sync`, to install the requirements to the target environment, which is a fresh virtualenv.

**Comment by davidovich** [comment]
No problem!
