### ISSUE TITLE
Add support for `pythonX.Y -m piptools ...`.

### ISSUE THREAD

**Issue by AndreLouisCaron** [jazzband/pip-tools#402]
I work with both Python 2.7 and Python 3.5 regularly.  The dependency resolution process uses the Python version in multiple different ways and I'm afraid that running with both might not give the same result depending on the Python version.

For this reason, I don't have a global alias to `pip-compile` _et al._.  I could of course use a virtualenv just for running piptools, but that's quite inconvenient (especially for projects that don't use Tox).   What I do have is a global alias to `pythonX.Y` (Linux) and `py -X.Y` (Windows).

The most convenient way to use pip-tools in this context is to support the `python -m piptools ...` CLI syntax, which requires a `piptools.__main__` module.

That way, when I work on a Python 2.7 project:

```
py -2.7 -m piptools compile requirements.txt  # compiles for Python 2.7
```

And when I switch to a Python 3.5 project:

```
py -3.5 -m piptools compile requirements.txt  # compiles for Python 3.5
```

Are you open to such a change if I'm willing to put some time into it?

Thanks!

**Comment by nvie** [comment]
This would be great. If anyone wants to contribute this, I'd encourage that.

**Comment by Groxx** [comment]
For virtualenvs-per-python-binary, have you seen pipsi?  https://github.com/mitsuhiko/pipsi
It essentially does this for you.  And there's a way to specify python 2/3 when doing so.  Very much recommended, since otherwise you end up polluting the global pip install with all kinds of incompatible stuff :|

Run-as-module is convenient in its own right tho, good idea!  And probably lots easier to use with automation.

**Comment by AndreLouisCaron** [comment]
@Groxx Didn't know about pipsi.  Thanks for the suggestion, but it's not quite what I'm looking for.
