### ISSUE TITLE
Version 1.8.1 and 1.9

### ISSUE THREAD

**Issue by davidovich** [jazzband/pip-tools#463]
Because we don't yet have an official communication channel, I am opening this issue to lay down what happened in the last few weeks:

* @nvie transferred maintainership to the jazzband organization.
* I started to cleanup the repo of old issues and started merging some bugfix only PRs in the 1.8.1 release
* I want to let the 1.8.1rc3 live for one week in order to be sure that it is safe to release.
* The next step would be to make a feature release 1.9.

Don't hesitate to comment, this is what it's all about !

**Comment by Groxx** [comment]
Very very glad to see this repo getting action again, thanks a bunch for diving in!  Is this an appropriate channel for general questions about all the goings on, or are you trying to keep it focused on 1.8.1 and 1.9 plans?

**Comment by davidovich** [comment]
We can focus on 1.8.1 and 1.9 for now, maybe open another ticket for more general ideas and directions we would like to take.

1.8.1 should bring a bit more stability in the resolver. I do not want to add other non bug fixing to this release. I think the rc3 will probably materialize next week if I don't hear anything more preventing it's release.

1.9 should bring small changes and features, there are a lot of good PRs, but some lack tests, and because of the new collaborative maintainership, I think it is a deal breaker for those. I am not sure what PRs are more important than others, I will survey the number of involvement and issue/PR participation and probably merge the best ones (with tests :-)).

Anybody wanting to be involved should open a request with jazzband, that will let them add Labels and close old tickets. There are really old issues that don't even apply anymore.

I am on vacation for the next 8 days, so I will not be able to participate that much.

**Comment by underyx** [comment]
Any chance of a 1.9.0 release soon? The merged https://github.com/jazzband/pip-tools/pull/441 would be super useful for us (and seemingly a lot of others, too).

There's this issue in the latest pip release, https://github.com/pypa/pip/issues/4264, which causes pip to fail when uninstalling appdirs (a setuptools dependency.) It takes quite a bit of duct tape to keep using pip-tools like this.

**Comment by davidovich** [comment]
@underyx I'm all for a 1.9 release, but I do not have alot of metrics for finalizing. 1.9 has a lot of new features and I wouldn't want to break anybody. I will create a rc1 for you to test. 

In the meantime, does installing on master fix your use cases ?

**Comment by underyx** [comment]
@davidovich yep, I can confirm that it's fixed on master. The RC will not be necessary — I can just keep using the commit from the latest master. It'd be a bit more inconvenient however to get everyone at the company to update each of their virtualenvs to a prerelease to make sure nobody overwrites `requirements.txt`s with versions that have `appdirs` in them.

**Comment by myw** [comment]
@davidovich Since you've mentioned it's a bit tricky to gather a sense of what will and won't break things when you're taking on an existing project like this, maybe the next release, currently called (1.9) should be 2.0? then people will know they have a risk of breaking when they upgrade, however low it may be, and do so a little more gingerly? it has a lot of new features already. Specifically, the one I'm interested in (pulling from `setup.py`) is a game-changer, in that it lets you use pip-tools in an existing project without the overhead of managing a separate requirements.in file. I wouldn't mind upgrading to 2.0 for the sake of having that feature.

Setting the next release at 2.0 lets you make the decision around finalization more easily—namely, in feature-space, not in issue-space. Once 2.0 is set, you can then start making smaller releases for the remaining features, adding them in one or two at a time, in minor version bumps, minimizing the chance of breakage.

**Comment by davidovich** [comment]
@myw Thanks for your suggestion, but I still feel this as being a 1.9, and as you say, the major feature is to support setup.py install_requires as a requirements.in. 
No new code entered without tests, so this brings confidence a bit up. I will be making a 1.9rc1 today (if time permits), which should also marinate a little while.

**Comment by davidovich** [comment]
1.9 is out, will close this. Thanks everyone!
