### ISSUE TITLE
Clarification re: installation

### ISSUE THREAD

**Issue by bhrutledge** [jazzband/pip-tools#582]
The README suggests `pip install pip-tools`, but it's not clear what environment that should be run in. Some of the options that I see:

1. System Python (e.g., distributed with OS): generally not recommended
2. Third-party Python (e.g., Homebrew, python.org, pyenv, Anaconda)
3. Virtual environment dedicated to pip-tools
4. Each project's virtual environment

In my case, I chose option 3, using [pipsi](https://github.com/mitsuhiko/pipsi) to streamline adding it to my PATH. I've installed other tools like fabric and cookiecutter in a similar manner, whereas I install things like flake8 using option 4.

I think option 1 or 2 would be safer with `pip install --user`.

**Comment by vphilippon** [comment]
Considering the `pip-sync` command, it needs to be installed in the same virtualenv that you want to `sync`, which is each project virtualenv, because `pip-sync` will simply perform packages install/uninstall in th current active environment.
That means option 4.

I don't know much about `pipsi`, but if tools installed with `pipsi` are available when in another virtualenv (like a given project's virtualenv), then it could work (or cause horrible unforeseen side-effect). If you want to give us you're feedback on how the `pip-sync` commands work in these condition, it could be good to know, and document if needed.

At the moment, I think that option 4 is the only fully valid option that will work with `pip-tools` as a whole (not only `pip-compile`). That should indeed be clarified in the doc.

**Comment by bhrutledge** [comment]
I've been using `pip-sync` successfully with `pipsi`, which I think makes sense based on your description. But, I'm happy to update the docs to suggest option 4, as that seems the easiest and least surprising.

On that note: is there any suggestion for including `pip-tools` as a development requirement in `setup.py` or a `.in` file?

**Comment by vphilippon** [comment]
@bhrutledge It might not seem like it, but that's a pretty loaded question right there. It points back to the broader question "how do I deal with dev requirements in Python", and there's not a single viewpoint on this in the community.

Although, I'm not an expert on all the fancy options available in `setup.py` using `setuptools`, but I would be very careful about including `pip-tools` somewhere in a `setup.py`. I would deal with `pip-tools` the same way you deal with `pip`. If there was a "dev_requires" section in `setup.py`, is could be an idea, although it would need some testing to make sure everything goes smoothely.

Personally, I keep my dev packages in a separate `dev_requirements.in`/`.txt`. But in the end, it comes down to using a way that fits your need, as long as you're aware that this is part of your "python environment tooling", like `pip` is.
