### ISSUE TITLE
Double requirement

### ISSUE THREAD

**Issue by mkolodny** [jazzband/pip-tools#620]
When we run `pip-compile` with a GitHub branch specified, and other libraries that depend on that library, we get two copies of the library in our `requirements.txt` file.

Specifically, we're trying to test out [a branch of `jaeger-client-python`](https://github.com/jaegertracing/jaeger-client-python/tree/unicode) from GitHub. In our `requirements.in` file, we require the library using pip's ["editable"](https://pip.pypa.io/en/latest/reference/pip_install/#editable-installs) mode:

`-e git+https://github.com/jaegertracing/jaeger-client-python.git@unicode#egg=jaeger-client-python`

Other libraries in our `requirements.in` file depend on `jaeger-client-python`. So when we run `pip-compile` to generate our `requirements.txt` file, we end up with two versions of `jaeger-client-python` in our `requirements.txt`:

    -e git+https://github.com/jaegertracing/jaeger-client-python.git@unicode#egg=jaeger-client-python
    jaeger-client-python==3.5.0

Is there a way to set up our `requirements.in` file so that running `pip-compile` only includes the editable dependency (`-e <url>`) in our `requirements.txt`?

**Comment by vphilippon** [comment]
This is pretty odd, there shouldn't be dupplicate.
One thing I noted though is that I can't find any PyPi distribution named `jaeger-client-python`, only `jaeger-client`. Plus, the branch you gave me provides a distribution named `jaeger-client` too (https://github.com/jaegertracing/jaeger-client-python/blob/unicode/setup.py#L19). 

By the way, are you sure that your other libs depend on `jaeger-client-python`, and not `jaeger-client`? Because, as I said, `jaeger-client-python` doesn't exist.

So, first, the editable requirement should end with `egg=jaeger-client`.
This could be the cause of the error, although I'm not quite sure why.

If this issue still occurs after changing the egg name, I'll need:
- the `pip-compile --verbose` output
- a requirements.in file to be able to reproduce (which includes other packages that depends on `jaeger-client`.), if you can provide one.

**Comment by mkolodny** [comment]
Great catch seeing that there's no PyPi distribution for `jaeger-client-python`. That helped a lot in finding the problem:

`jaeger-client-python` is actually an internal company python package that depends on `jaeger-client`. So there was no duplicate - they're different packages with very similar names.
