### ISSUE TITLE
pip-sync ignores option --no-binary

### ISSUE THREAD

**Issue by merwok** [jazzband/pip-tools#637]
psycopg2 wheel gets installed in spite of the `--no-binary psycopg2` option.

##### Environment Versions

1. OS: Debian
1. Python version: 3.6.4
1. pip version: 9.01
1. pip-tools version: 1.11.0

##### Steps to replicate

1. Create deps.in with line `psycopg2 --no-binary psycopg2`
2. Run `pip-compile deps.in`, see that the flag is preserved in the txt file
3. Run `pip-sync deps.txt`

##### Expected result

A psycopg2 sdist is installed.  `pip install -r deps.txt` does that.

##### Actual result

A psycopg2 wheel is installed.

**Comment by merwok** [comment]
Ticket #638 is the same issue with a more generic title.

**Comment by estan** [comment]
I bumped into this limitation again today and decided to have a look at it. Turns out it's not so easy since the pip API that pip-sync is using to parse the requirements files (`parse_requirements`) does not provide the info about any encountered `--no-binary` flags out-of-the box, so fixing it would take some refactoring.

**Comment by atugushev** [comment]
I've prepared a pull request (#824), which adds support of `--no-binary` and the other options. Any feedback, review/test would be appreciated!
