### ISSUE TITLE
ImportError: No module named req if pip is imported before piptools.utils

### ISSUE THREAD

**Issue by vlovich** [jazzband/pip-tools#661]
Describe the issue briefly here.
If pip is imported before piptools, piptools doesn't properly import.

##### Environment Versions

1. OS Type macOS 10.13.4
1. Python version: `$ python -V` 2.7.10
1. pip version:  `$ pip --version` pip 10.0.1
1. pip-tools version: `$ pip-compile --version` 2.0.2

##### Steps to replicate

1. import pip
2. import piptools.utils

##### Expected result
Should import fine.

##### Actual result
    >>> import piptools.utils
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/Users/vlovich/Library/Python/2.7/lib/python/site-packages/piptools/utils.py", line 9, in <module>
        from pip.req import InstallRequirement
    ImportError: No module named req

**Comment by vphilippon** [comment]
Hi @vlovich and @MichaelAquilina , thanks for the report.

I was able to reproduce. on `pip-tools 2.0.2` . I expect this to be fixed in our next `3.0.0` release, as we've undone the `pip` vendoring mechanic that likely caused this. I'll try to get the release out soon.

In the meantime, you can test by installing from the HEAD of master.
Cheers!

**Comment by vphilippon** [comment]
This should be fixed in version `3.1.0`. Tell us if it's still happening.

Cheers!
