### ISSUE TITLE
pip-compile updates to pre-release version without --pre flag

### ISSUE THREAD

**Issue by nbelakovski** [jazzband/pip-tools#691]
If a package is pinned at >=(some pre-release version), running pip-compile will grab the latest pre-release version of that package, as opposed to the latest release, even if the --pre flag is not specified.

##### Environment Versions

1. Linux
1. Python version: 2.7.12
1. pip version:  18.1
1. pip-tools version: 2.0.2

##### Steps to replicate

1. echo "coverage>=4.0a6" > requirements.in
2. pip-compile | grep coverage

##### Expected result

coverage==4.5.1 (at the time of this writing)

##### Actual result

coverage==5.0a3 (at the time of this writing)

Compare https://github.com/nedbat/coveragepy/releases against the date of this issue to get an idea of which versions of coverage were available at the time of writing.
If requirements.in has "coverage>=4.0", then you get 4.5.1 as expected. Also, if requirements.in has "coverage>4.0a6" (> instead of >=) then you get 4.5.1 as expected (in some cases with that one I got 5.0a3, but I'm not able to replicate anymore)

**Comment by nbelakovski** [comment]
I'm having varying results in replicating this on different machines, but it seems that adding --rebuild and --upgrade to the pip-compile command help with reproducibility.

**Comment by di** [comment]
I think I'm experiencing this issue as well (at the time of writing, with `pyramid` which just released a prerelease). I tried pinning `pip` back to 18.0 and the issue persists, so it seems like this is coming from the `pip-tools==3.0.1` release.

I'm also having trouble reproducing this though, and the behavior I'm seeing is not that the prerelease version is getting pinned, but that a sub-dependency that has been removed in the pre-release is being removed from the compiled file.

**Comment by di** [comment]
Hmm, just noticed that @nbelakovski is using `pip-tools==2.0.2` though... ¯\\\_(ツ)_/¯

**Comment by atugushev** [comment]
Hello @nbelakovski,

Thanks for the good catch. I've been digging into it and have found something.

That's because `pre is None` by default, see:
https://github.com/jazzband/pip-tools/blob/master/piptools/scripts/compile.py#L36

If pre is None, so pre-release flag for compiled requirement gets value from current requirement specifier `coverage>=4.0a6` (read as `ireq.req.specifier.prelereases = True`), then version resolver treat this package as pre-released and finally tries to find best version including pre-released packages, see `filter` method:
https://github.com/pypa/pip/blob/master/src/pip/_vendor/packaging/specifiers.py#L708-L709

If the flag had been False value, the version resolver would have looked among "non-pre-released" packages.

I think it should be False by default.

**Comment by nbelakovski** [comment]
Looking through that PR, if I understand it correctly, I think that the behavior is correct if, using the example above, 4.0a6 was the latest version of the coverage library. If that were the case, the pin would break without --pre. But assuming 4.0 or a higher production release is available, then pip-compile should no longer look for pre-release packages.

**Comment by atugushev** [comment]
@nbelakovski 
Yes, I suppose so. Anyways, thank for the report. I found it interesting.
