### ISSUE TITLE
Pin setuptools in test_allow_unsafe_option

### ISSUE THREAD

**Issue by webknjaz** [jazzband/pip-tools#988]
FTR, would be nice to pin setuptools here as well, but it would take to rewrite the test.

_Originally posted by @atugushev in https://github.com/jazzband/pip-tools/pull/975_

**Comment by atugushev** [comment]
Should be fixed after #990.

**Comment by atugushev** [comment]
@hramezani would you be interested in this issue as a followup #990? 

Since `test_allow_unsafe_option` has been already refactored we can pin now the package (`small-fake-a`) in parameters and make `test_allow_unsafe_option ` test more assertive:

```python
...
[("--allow-unsafe", "\nsmall-fake-a==0.1"), (None, "\n# small-fake-a")],
...
assert expected in out.stderr.splitlines()
```

Also, would be nice to fix `test_local_url_package` the same way.

**Comment by hramezani** [comment]
@atugushev yes, Just assign it to me.

**Comment by atugushev** [comment]
@hramezani, thanks!
